#!/bin/bash

echo "Start docker:"
echo "docker-sync start"
echo "docker-compose -f docker-compose.yml -f docker-compose-dev.yml up"
echo ""
echo "clean docker-sync :"
echo "docker-sync clean"
echo "docker-sync start"
echo ""
echo "connect container www-data:"
echo "docker exec -it -u www-data myproject-phpfpm /bin/bash"
echo "docker exec -it -u www-data myproject-db /bin/bash"
echo "docker exec -it -u www-data myproject-nginx /bin/bash"
echo "docker exec -it -u www-data myproject-elasticsearch /bin/bash"
echo ""
echo "connect container root:"
echo "docker exec -it -u root myproject-phpfpm /bin/bash"
echo "docker exec -it -u root myproject-db /bin/bash"
echo "docker exec -it -u root myproject-nginx /bin/bash"
echo "docker exec -it -u root myproject-elasticsearch /bin/bash"

echo "connect container root:"
echo "docker exec -i myproject-db mysql -umyproject -pmyproject1234 myproject < myproject.sql"
